name: 批量保活进程

on:
  schedule:
    # 使用cron表达式定义任务运行的时间
    # github使用utc时间
    - cron: '3 22 * * *' #北京时间6点
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get install sshpass
          sudo apt-get install jq

      - name: 登录各个serv00并执行保活脚本
        env:
          HOSTS_JSON: ${{ secrets.HOSTS_JSON }}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_USERID: ${{secrets.TELEGRAM_USERID}}
          WXSENDKEY: ${{secrets.WXSENDKEY}}
          SENDTYPE: ${{secrets.SENDTYPE}}
          BUTTON_URL: ${{secrets.BUTTON_URL}}
          AUTOUPDATE: ${{vars.AUTOUPDATE}}
        run: |
          chmod +x ./revive.sh
          ./revive.sh
